test:test.c json_object.c debug.c arraylist.c json_c_version.c json_object_iterator.c json_tokener.c json_util.c libjson.c linkhash.c printbuf.c 
	gcc -o test test.c json_object.c debug.c arraylist.c json_c_version.c json_object_iterator.c json_tokener.c json_util.c libjson.c linkhash.c printbuf.c   
clean:
	rm test
